import "dotenv/config";
import { PrismaClient } from "@prisma/client";

const QUESTIONS = [
  { id: "q001", categoryId: "money", displayOrder: 1, questionText: "買い物をするとき、気分よりも納得感を重視するほうだ。", reverseScore: false },
  { id: "q002", categoryId: "money", displayOrder: 2, questionText: "毎月の支出をだいたい把握している。", reverseScore: false },
  { id: "q003", categoryId: "money", displayOrder: 3, questionText: "将来のために、今の楽しみを我慢することに抵抗はない。", reverseScore: false },
  { id: "q004", categoryId: "money", displayOrder: 4, questionText: "パートナーとはお金の使い方についてオープンに話し合いたい。", reverseScore: false },
  { id: "q005", categoryId: "money", displayOrder: 5, questionText: "衝動買いをして後悔することがよくある。", reverseScore: true },
  { id: "q006", categoryId: "money", displayOrder: 6, questionText: "貯蓄や資産管理について自分なりの考えがある。", reverseScore: false },
  { id: "q007", categoryId: "money", displayOrder: 7, questionText: "割り勘や費用分担のルールは明確にしておきたい。", reverseScore: false },
  { id: "q008", categoryId: "money", displayOrder: 8, questionText: "大きな買い物は、十分に比較検討してから決める。", reverseScore: false },
  { id: "q009", categoryId: "money", displayOrder: 9, questionText: "お金のことで不安を感じることがある。", reverseScore: false },
  { id: "q010", categoryId: "money", displayOrder: 10, questionText: "経済的に自立していることは、パートナー選びの重要な条件だ。", reverseScore: false },
  { id: "q011", categoryId: "food", displayOrder: 1, questionText: "食事の時間は、一日の中で特に大切にしている。", reverseScore: false },
  { id: "q012", categoryId: "food", displayOrder: 2, questionText: "食材の産地や品質が気になるほうだ。", reverseScore: false },
  { id: "q013", categoryId: "food", displayOrder: 3, questionText: "外食よりも自炊のほうが好きだ。", reverseScore: false },
  { id: "q014", categoryId: "food", displayOrder: 4, questionText: "パートナーとは食の好みが合うことが大切だと思う。", reverseScore: false },
  { id: "q015", categoryId: "food", displayOrder: 5, questionText: "健康のために食事内容を意識している。", reverseScore: false },
  { id: "q016", categoryId: "food", displayOrder: 6, questionText: "新しい料理やお店を試すのが好きだ。", reverseScore: false },
  { id: "q017", categoryId: "food", displayOrder: 7, questionText: "食事中はスマホを見ないで会話を楽しみたい。", reverseScore: false },
  { id: "q018", categoryId: "food", displayOrder: 8, questionText: "料理を作ることに喜びを感じる。", reverseScore: false },
  { id: "q019", categoryId: "food", displayOrder: 9, questionText: "食べることにはあまりこだわりがない。", reverseScore: true },
  { id: "q020", categoryId: "food", displayOrder: 10, questionText: "食卓を囲む時間は、家族やパートナーとの大切なコミュニケーションだ。", reverseScore: false },
  { id: "q021", categoryId: "family", displayOrder: 1, questionText: "将来は家庭を持ちたいと思っている。", reverseScore: false },
  { id: "q022", categoryId: "family", displayOrder: 2, questionText: "家族との時間を最も優先したい。", reverseScore: false },
  { id: "q023", categoryId: "family", displayOrder: 3, questionText: "親や兄弟との関係は大切にしたい。", reverseScore: false },
  { id: "q024", categoryId: "family", displayOrder: 4, questionText: "パートナーの家族とも良好な関係を築きたい。", reverseScore: false },
  { id: "q025", categoryId: "family", displayOrder: 5, questionText: "家事や育児は平等に分担するべきだと思う。", reverseScore: false },
  { id: "q026", categoryId: "family", displayOrder: 6, questionText: "子どもを持つことについて具体的に考えたことがある。", reverseScore: false },
  { id: "q027", categoryId: "family", displayOrder: 7, questionText: "家庭では安心してリラックスできる空間を大切にしたい。", reverseScore: false },
  { id: "q028", categoryId: "family", displayOrder: 8, questionText: "結婚は人生の大きな目標のひとつだ。", reverseScore: false },
  { id: "q029", categoryId: "family", displayOrder: 9, questionText: "ペットを飼うことに興味がある。", reverseScore: false },
  { id: "q030", categoryId: "family", displayOrder: 10, questionText: "パートナーとは対等な関係でいたい。", reverseScore: false },
  { id: "q031", categoryId: "selfcare", displayOrder: 1, questionText: "定期的に運動する習慣がある。", reverseScore: false },
  { id: "q032", categoryId: "selfcare", displayOrder: 2, questionText: "睡眠の質にはこだわっている。", reverseScore: false },
  { id: "q033", categoryId: "selfcare", displayOrder: 3, questionText: "ストレスを感じたとき、自分なりの対処法を持っている。", reverseScore: false },
  { id: "q034", categoryId: "selfcare", displayOrder: 4, questionText: "体調管理は自己責任だと思う。", reverseScore: false },
  { id: "q035", categoryId: "selfcare", displayOrder: 5, questionText: "メンタルヘルスについて意識して気をつけている。", reverseScore: false },
  { id: "q036", categoryId: "selfcare", displayOrder: 6, questionText: "ひとりの時間を持つことが心の安定に必要だ。", reverseScore: false },
  { id: "q037", categoryId: "selfcare", displayOrder: 7, questionText: "健康診断は定期的に受けている。", reverseScore: false },
  { id: "q038", categoryId: "selfcare", displayOrder: 8, questionText: "パートナーにも健康への意識を持っていてほしい。", reverseScore: false },
  { id: "q039", categoryId: "selfcare", displayOrder: 9, questionText: "自分の感情の変化に敏感なほうだ。", reverseScore: false },
  { id: "q040", categoryId: "selfcare", displayOrder: 10, questionText: "リフレッシュの仕方を自分でわかっている。", reverseScore: false },
  { id: "q041", categoryId: "career", displayOrder: 1, questionText: "仕事にやりがいを感じることは重要だ。", reverseScore: false },
  { id: "q042", categoryId: "career", displayOrder: 2, questionText: "キャリアアップのために努力を惜しまない。", reverseScore: false },
  { id: "q043", categoryId: "career", displayOrder: 3, questionText: "ワークライフバランスを大切にしたい。", reverseScore: false },
  { id: "q044", categoryId: "career", displayOrder: 4, questionText: "パートナーの仕事への理解は大切だと思う。", reverseScore: false },
  { id: "q045", categoryId: "career", displayOrder: 5, questionText: "将来は独立や起業を考えたことがある。", reverseScore: false },
  { id: "q046", categoryId: "career", displayOrder: 6, questionText: "安定した収入よりも、やりたいことを優先したい。", reverseScore: false },
  { id: "q047", categoryId: "career", displayOrder: 7, questionText: "仕事を通じて社会に貢献したいと思う。", reverseScore: false },
  { id: "q048", categoryId: "career", displayOrder: 8, questionText: "転職や職種変更に抵抗は少ないほうだ。", reverseScore: false },
  { id: "q049", categoryId: "career", displayOrder: 9, questionText: "仕事のストレスをパートナーに相談できる関係が理想だ。", reverseScore: false },
  { id: "q050", categoryId: "career", displayOrder: 10, questionText: "パートナーのキャリアも応援したいと思う。", reverseScore: false },
  { id: "q051", categoryId: "leisure", displayOrder: 1, questionText: "休日は外出するより家で過ごすことが多い。", reverseScore: false },
  { id: "q052", categoryId: "leisure", displayOrder: 2, questionText: "趣味に没頭する時間を大切にしている。", reverseScore: false },
  { id: "q053", categoryId: "leisure", displayOrder: 3, questionText: "パートナーとは趣味を共有したい。", reverseScore: false },
  { id: "q054", categoryId: "leisure", displayOrder: 4, questionText: "旅行や新しい体験にお金を使うのは惜しくない。", reverseScore: false },
  { id: "q055", categoryId: "leisure", displayOrder: 5, questionText: "読書や映画など、ひとりで楽しめる趣味がある。", reverseScore: false },
  { id: "q056", categoryId: "leisure", displayOrder: 6, questionText: "アウトドアやスポーツ観戦が好きだ。", reverseScore: false },
  { id: "q057", categoryId: "leisure", displayOrder: 7, questionText: "予定を入れすぎず、余白のある生活が好きだ。", reverseScore: false },
  { id: "q058", categoryId: "leisure", displayOrder: 8, questionText: "パートナーとは別々の趣味を持っていてもよいと思う。", reverseScore: false },
  { id: "q059", categoryId: "leisure", displayOrder: 9, questionText: "季節の行事やイベントを楽しむほうだ。", reverseScore: false },
  { id: "q060", categoryId: "leisure", displayOrder: 10, questionText: "自分の時間を自由に使えることが幸せだと感じる。", reverseScore: false },
  { id: "q061", categoryId: "society", displayOrder: 1, questionText: "地域のコミュニティ活動に関心がある。", reverseScore: false },
  { id: "q062", categoryId: "society", displayOrder: 2, questionText: "社会問題について考えることがある。", reverseScore: false },
  { id: "q063", categoryId: "society", displayOrder: 3, questionText: "ボランティアや社会貢献活動に興味がある。", reverseScore: false },
  { id: "q064", categoryId: "society", displayOrder: 4, questionText: "多様な価値観を受け入れることは大切だと思う。", reverseScore: false },
  { id: "q065", categoryId: "society", displayOrder: 5, questionText: "友人関係は広く浅くより、狭く深くが好みだ。", reverseScore: false },
  { id: "q066", categoryId: "society", displayOrder: 6, questionText: "環境問題について意識して行動している。", reverseScore: false },
  { id: "q067", categoryId: "society", displayOrder: 7, questionText: "パートナーとは社会的な価値観が近いほうがよい。", reverseScore: false },
  { id: "q068", categoryId: "society", displayOrder: 8, questionText: "近所づきあいは大切にしたい。", reverseScore: false },
  { id: "q069", categoryId: "society", displayOrder: 9, questionText: "社会のルールやマナーを守ることは当然だと思う。", reverseScore: false },
  { id: "q070", categoryId: "society", displayOrder: 10, questionText: "人とのつながりが人生を豊かにすると感じる。", reverseScore: false },
  { id: "q071", categoryId: "curiosity", displayOrder: 1, questionText: "新しいことに挑戦するのが好きだ。", reverseScore: false },
  { id: "q072", categoryId: "curiosity", displayOrder: 2, questionText: "知らない場所に行くとワクワクする。", reverseScore: false },
  { id: "q073", categoryId: "curiosity", displayOrder: 3, questionText: "計画を立てるよりも、直感で動くことが多い。", reverseScore: false },
  { id: "q074", categoryId: "curiosity", displayOrder: 4, questionText: "失敗を恐れずにまずやってみるタイプだ。", reverseScore: false },
  { id: "q075", categoryId: "curiosity", displayOrder: 5, questionText: "パートナーとは一緒に新しい経験をしたい。", reverseScore: false },
  { id: "q076", categoryId: "curiosity", displayOrder: 6, questionText: "変化のある生活のほうが刺激的で好きだ。", reverseScore: false },
  { id: "q077", categoryId: "curiosity", displayOrder: 7, questionText: "異文化や異なる考え方に触れることが好きだ。", reverseScore: false },
  { id: "q078", categoryId: "curiosity", displayOrder: 8, questionText: "同じルーティンの繰り返しは退屈に感じる。", reverseScore: false },
  { id: "q079", categoryId: "curiosity", displayOrder: 9, questionText: "リスクを取ってでも面白いことをしたい。", reverseScore: false },
  { id: "q080", categoryId: "curiosity", displayOrder: 10, questionText: "好奇心が行動の原動力になっている。", reverseScore: false },
  { id: "q081", categoryId: "growth", displayOrder: 1, questionText: "自己啓発や学びに時間を投資している。", reverseScore: false },
  { id: "q082", categoryId: "growth", displayOrder: 2, questionText: "本やポッドキャストなどで学ぶのが好きだ。", reverseScore: false },
  { id: "q083", categoryId: "growth", displayOrder: 3, questionText: "フィードバックを受け入れて改善できるほうだ。", reverseScore: false },
  { id: "q084", categoryId: "growth", displayOrder: 4, questionText: "目標を設定して計画的に取り組むことが多い。", reverseScore: false },
  { id: "q085", categoryId: "growth", displayOrder: 5, questionText: "パートナーとは互いに高め合える関係が理想だ。", reverseScore: false },
  { id: "q086", categoryId: "growth", displayOrder: 6, questionText: "過去の失敗から学びを得るほうだ。", reverseScore: false },
  { id: "q087", categoryId: "growth", displayOrder: 7, questionText: "新しいスキルを身につけることに喜びを感じる。", reverseScore: false },
  { id: "q088", categoryId: "growth", displayOrder: 8, questionText: "自分の弱点を把握して克服しようとする。", reverseScore: false },
  { id: "q089", categoryId: "growth", displayOrder: 9, questionText: "成長のためにコンフォートゾーンを出ることが必要だと思う。", reverseScore: false },
  { id: "q090", categoryId: "growth", displayOrder: 10, questionText: "人生には常に学ぶべきことがあると感じる。", reverseScore: false },
  { id: "q091", categoryId: "communication", displayOrder: 1, questionText: "自分の気持ちを言葉にして伝えるのが得意だ。", reverseScore: false },
  { id: "q092", categoryId: "communication", displayOrder: 2, questionText: "相手の話をじっくり聞くほうだ。", reverseScore: false },
  { id: "q093", categoryId: "communication", displayOrder: 3, questionText: "意見が合わないとき、話し合いで解決したい。", reverseScore: false },
  { id: "q094", categoryId: "communication", displayOrder: 4, questionText: "LINEやメッセージの返信は早いほうだ。", reverseScore: false },
  { id: "q095", categoryId: "communication", displayOrder: 5, questionText: "パートナーとは毎日何かしら会話をしたい。", reverseScore: false },
  { id: "q096", categoryId: "communication", displayOrder: 6, questionText: "本音を話せる関係が一番大切だと思う。", reverseScore: false },
  { id: "q097", categoryId: "communication", displayOrder: 7, questionText: "沈黙が続いても気まずさを感じない。", reverseScore: false },
  { id: "q098", categoryId: "communication", displayOrder: 8, questionText: "感謝の気持ちを言葉で伝えるほうだ。", reverseScore: false },
  { id: "q099", categoryId: "communication", displayOrder: 9, questionText: "相手の非言語サイン（表情や態度）に気づくほうだ。", reverseScore: false },
  { id: "q100", categoryId: "communication", displayOrder: 10, questionText: "困ったときに素直に助けを求められる。", reverseScore: false },
];

async function main() {
  const prisma = new PrismaClient();

  // 質問データをupsert
  for (const q of QUESTIONS) {
    await prisma.diagnosisQuestion.upsert({
      where: { id: q.id },
      update: {
        categoryId: q.categoryId,
        displayOrder: q.displayOrder,
        questionText: q.questionText,
        reverseScore: q.reverseScore,
      },
      create: {
        id: q.id,
        categoryId: q.categoryId,
        displayOrder: q.displayOrder,
        questionText: q.questionText,
        reverseScore: q.reverseScore,
        activeFlag: true,
      },
    });
  }

  console.log(`Seeded ${QUESTIONS.length} questions`);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
